# Generated by Django 2.1 on 2018-09-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_remove_service_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='contenido',
            new_name='content',
        ),
    ]
